### ISSUE TITLE
DELL capsule update failed: Unknown error -1 (maybe fwupx64.efi)

### ISSUE THREAD

**Issue by cinghiopinghio** [hughsie/fwupd#105]
I'm trying to update my bios (Dell xps 9550 + Archlinux) but I get the following error:
```
Downloading 5.81.2.1 for XPS 15 9550 TPM 1.2...
Updating 5.81.2.1 on XPS 15 9550 TPM 1.2...
Decompressing…         
Retrying as an offline update...
Scheduling…            
DELL capsule update failed: Unknown error -1
```

After reading around in the Issue tracker there is probably a problem with the location of `fwupx64.efi` which is not on `boot`:
```
> tree /boot
/boot
├── EFI
│   ├── Boot
│   │   └── BOOTX64.EFI
│   └── systemd
│       └── systemd-bootx64.efi
├── initramfs-linux-fallback.img
├── initramfs-linux.img
├── intel-ucode.img
├── loader
│   ├── entries
│   │   └── arch.conf
│   └── loader.conf
└── vmlinuz-linux
```

As mentioned here https://github.com/hughsie/fwupd/issues/75, the relevant file can be found on `/usr/lib/fwupdate/EFI/arch` but copying it to `/boot/EFI/arch` or `/boot/EFI/Arch` didn't help.

I'm using:
```
efivar 31-1
fwupd 0.8.1
fwupdate 9-1
```
Any clue?

**Comment by superm1** [comment]
I think this is the exact same issue as #75 was. Checking through the history that was led over to https://github.com/rhinstaller/fwupdate/issues/58 which is still waiting for a patch from someone affected to allow configuring alternate locations.

As it stands right now fwupdate (and libfwup) will at compile time be configure where they will look for the EFI bootloader used for calling UpdateCapsule.  If those aren't found, that's when this error comes up.  

In terms of your manual test I don't think you necessarily got it right either.
https://github.com/rhinstaller/fwupdate/blob/master/linux/libfwup.c#L705
shows the path it should be look at.

I'm going to mark this closed on fwupd project since the error still lies in fwupdate and the way that Arch is working with it.  If you're got the cycles and skills, pjones was looking for help on creating a patch on that bug.
