### ISSUE TITLE
fwupdmgr TBT can not verify update - should wake up controller again

### ISSUE THREAD

**Issue by gsgxnet** [hughsie/fwupd#457]
I was successful updating on a DELL Precision 5520 OS openSUSE Tumbleweed the TBT firmware from 21.01 to 26.01. But the `fwupdmgr` stated:

`fwupdmgr install TBTfirmware426.cab`   
(a .cab created by me from the newest DELL tbt fw from their support site, with the packager tool)
```
Decompressing…         [***************************************]
Authenticating…        [***************************************]
Restarting device…     [***************************************]
could not detect device after update: timed out while waiting for device  
```
this is a false error report, after a new start all is fine, see below the get-devices output.
My assumption is the `fwupd` daemon forces a wake-up of the controller when started. After a successful fw update the controller might enter sleep mode again. This might cause the reported false error. 

---

To help us pinpoint your issue, please insert the output of the
following commands when ran on the system with the issue:

```shell
$ fwupdmgr --version
client version: 1.0.6
daemon version: 1.0.6
compile-time dependency versions
        appstream-glib: 0.7.7
        gusb:   0.3.0
        fwupdate:       9
        efivar: 31
```

```shell
$ fwupdmgr get-devices

Intel AMT [unprovisioned]
  DeviceId:             088df415cdee883ec89563e41e6d495924250174
  Guid:                 2800f812-b7b4-2d4b-aca8-46e0ff65814c
  Summary:              Hardware and firmware technology for remote out-of-band management
  Plugin:               amt
  Flags:                internal|registered
  Vendor:               Intel Corporation
  Version:              11.8.50
  VersionBootloader:    11.8.50
  Icon:                 computer
  Created:              2018-04-09

Precision 5520 System Firmware
  DeviceId:             f49999b6e3af5b4bf8ad1f2ed2922b76df457271
  Guid:                 34578c72-11dc-4378-bc7f-b643866f598c
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|registered|needs-reboot
  Version:              0.1.7.1
  VersionLowest:        0.1.7.1
  Icon:                 computer
  Created:              2018-04-09

GM107GLM [Quadro M1200 Mobile]
  DeviceId:             3f0f51a4f03bccdad9f8ae1334bad4584b5ba875
  Guid:                 f201385b-abb8-522b-b393-a11c2bdb4ca8
  Plugin:               udev
  Flags:                internal|registered
  Vendor:               NVIDIA Corporation
  VendorId:             PCI:0x10DE
  Icon:                 audio-card
  Created:              2018-04-09

HD Graphics P630
  DeviceId:             8de6c7959053fd5798006dcc63590d33fa5e51cb
  Guid:                 7d7e2d9f-fbbd-5ef5-bd6f-ff05053131cf
  Plugin:               udev
  Flags:                internal|registered
  Vendor:               Intel Corporation
  VendorId:             PCI:0x8086
  Icon:                 audio-card
  Created:              2018-04-09

Precision M5520 Thunderbolt Controller
  DeviceId:             42690f057c2579c71a5cc206040b20d29dd06d10
  Guid:                 c5364422-2ec3-5092-b30e-03bdb1a53e4a
  Summary:              Unmatched performance for high-speed I/O
  Plugin:               thunderbolt
  Flags:                internal|updatable|supported|registered
  Vendor:               Dell
  VendorId:             TBT:0x00D4
  Version:              26.01
  Icon:                 computer
  Created:              2018-04-09

```
...

Please answer the following questions:

- Operating system and version: openSUSE TW 20180404
- How did you install fwupd (ex: `from source`, `pacman`, `apt-get`, etc): `rpm` from SUSE repo
- Have you tried rebooting? -- / yes
- Are you using an NVMe disk? yes
- Is secure boot enabled (only for the UEFI plugin)? --

**Comment by superm1** [comment]
Did it update successfully and just not come back during upgrade? Eg is it updated right now? Or after reboot if it back upgraded?

**Comment by superm1** [comment]
Sorry, I misread your original post, you already answered my questions.  Yes the controller was updated successfully. 

Yes the daemon does use force power to turn on the controller before the update starts.  We currently expect that force power persists after the update is complete.

@YehezkelShB do you know is that a poor assumption?

@gsgxnet I would be interested if you can reproduce this readily trying to reinstall the same CAB file (you may need to use `--allow-reinstall` flag to do this).  If you can reproduce this can you please do the following:
1. Stop your fwupd.service
2. Start the service with verbose mode (either modify systemd unit or manually launch with the `-v` flag)
3. Share the fwupd verbose output while this error happens
4. While in the bad state:
a. check `/sys/bus/thunderbolt` devices
b. Please share `dmesg`
c. Try to manually apply force power again and see if it helps the situation (you should see stuff show up in `/sys/bus/thunderbolt` if so).  See https://github.com/torvalds/linux/blob/master/Documentation/admin-guide/thunderbolt.rst for directions on how to manually do this.

**Comment by superm1** [comment]
CC @finikorg too on this question.

**Comment by YehezkelShB** [comment]
Force-power state shouldn't be affected by the FW update process.
Iassume we never unset force-power somewhere in the update process, do we?

**Comment by superm1** [comment]
It's turned on via `update_prepare` and turned off via `update_cleanup`.

That said I do see a series of events that I hypothesize might cause a problem.  
1. User starts up the system and fwupd doesn't start automatically.
2. User manually calls `fwupdmgr install blah.cab` (or `fwupdmgr update` really) which uses dbus activation to start fwupd systemd unit.
3. This runs coldplug on thunderbolt plugin, no devices found.
4. Thunderbolt power runs coldplug routine.
a. This sets forcepower with a timeout to turn off after 20 seconds.
b. Coldplug exits.
5. update routine starts.
a. Thunderbolt plugin starts flash routine.
b. Thunderbolt power plugin turns off force power in middle of flash routine.
c. Issue described happens.

Because of the series of events and timing that would be required to lead to this, you probably couldn't reproduce by manually running fwupd -v to see the logs, you would need to use dbus activation to reproduce it.

So @gsgxnet instead of what I mentioned in my other comment can you please follow this set of steps to try to reproduce:
0. Make sure nothing plugged into the TBT port.
1. Modify systemd unit for fwupd to add verbose flag (-v)
2. Make sure systemd unit is stopped (if not, stop it)
3. Run fwupdmgr install `blah.cab --allow-reinstall`
4. If the problem reproduced, please share the journal output for the fwupd unit.

We should see in the log `Setting force power to` indicating that force power was modified mid update if that's a correct hypothesis.

**Comment by superm1** [comment]
@gsgxnet We've merged my proposed fix for this (that assumes my hypothesis was right)  can you please try to reproduce again as I outlined above with your current version?  If you can reproduce can you please apply https://github.com/hughsie/fwupd/commit/0bd8c74cc0b7aa10e1cd74b54afabe6528ed5a46 and try again and see if it fixes the problem for you?  Thanks!

**Comment by gsgxnet** [comment]
Remark:  
when assembling the `.cab` I had followed the instructions found in your `contrib` folder: https://github.com/hughsie/fwupd/tree/master/contrib/firmware-packager  
Probably had set the `--realese-version` to something other than what is the real version. This allows repeated updates without the `--allow-reinstall` switch. Funny.

**Comment by superm1** [comment]
That's actually wonderful!  Reproducing with the network adapter plugged in probably influences fwupd's coldplug timing which plays into this problem.

Looking at your order of events:

1. Initially turn on force power at startup.
```
Apr 10 22:08:03 D3L3 fwupd[19044]: 22:08:03:0264 ThunderboltPower Setting force power to 1
```

2. Install command received
```
Apr 10 22:08:03 D3L3 fwupd[19044]: 22:08:03:0498 Fu  Called Install(*,7)
```

3. Device isn't ready yet so nothing is called, and it times out and powers off (that's your first error message)
```
Apr 10 22:08:23 D3L3 fwupd[19044]: 22:08:23:0271 ThunderboltPower Setting force power to 0
```

4. You call install again
```
Apr 10 22:08:29 D3L3 fwupd[19044]: 22:08:29:0542 Fu  Called Install(*,7)
```

5. Force power is turned on again
```
Apr 10 22:08:29 D3L3 fwupd[19044]: 22:08:29:0547 ThunderboltPower Setting force power to 1
```

6.  Device updated properly and is restarting, and a recoldplug is scheduled mid probe.
```
Apr 10 22:08:40 D3L3 fwupd[19044]: 22:08:40:0003 Fu  scheduling a recoldplug
```

7.  During the recoldplug force power is turned back on:
```
Apr 10 22:08:42 D3L3 fwupd[19044]: 22:08:42:0053 ThunderboltPower Setting force power to 1
```

8. 20 seconds later it's turned off:
```
Apr 10 22:09:02 D3L3 fwupd[19044]: 22:09:02:0056 ThunderboltPower Setting force power to 0
```

9. Finally it's turned off again after update_cleanup is run:
```
Apr 10 22:09:39 D3L3 fwupd[19044]: 22:09:39:0982 ThunderboltPower Setting force power to 0
```
The device is already gone though because it got turned off during the recoldplug.

So what do I make sense of that?

Well it's caused specifically because the recoldplug happened.  That happened because the ethernet device you have shares the same VID/PID as the Dell dock which needs a recoldplug for Synaptics MST to work.
You can make two arguments about root cause and where to fix it:

1. Thunderbolt power shouldn't recoldplug (ever)
2. The scheduled recoldplug shouldn't run on dongles, but only if the TB16 or WD15 are found.  I know the TB16 can be identified by bcdDevice and iSerial (https://github.com/torvalds/linux/commit/0b1655143df00ac5349f27b765b2ed13a3ac40ca#diff-d45f6c5dfa1088acc4fb00e7636dbba7) and I would anticipate that WD15 can be too.

**Comment by gsgxnet** [comment]
> That happened because the ethernet device you have shares the same VID/PID as the Dell dock which needs a recoldplug for Synaptics MST to work

Funny - the ethernet USB-C adapter is the original DELL device which came with the laptop. Dell's fault to assign same VID/PID to 2 different adapters?

**Comment by superm1** [comment]
No fault.
It's the same Realtek chip in the WD15, TB16, and the dongle that came with your machine.  The way to distinguish the 3 is those extra USB descriptor details.

**Comment by superm1** [comment]
Alright so I've got that fix ^ that should do <1> in my root cause analysis.  Doing <2> is a good idea too, but it will require more digging because the USB device needs to be opened already to get that information which doesn't currently happen early enough.

**Comment by gsgxnet** [comment]
Great you could fix the issue. I will close it for now.

Regarding the usb-eth adapter. These Realtek are not my favorites. A year ago there was a big issue in the rtl8152 driver. Kernel panic reproduceable:

Apr 16 09:58:27 linux-hcrp kernel: BUG: unable to handle kernel NULL pointer dereference at 0000000000000008
    Apr 16 09:58:27 linux-hcrp kernel: IP: r8152_poll+0x126/0x560 [r8152]

Nowdays it does not wake up after a resume, I have to either replug it or sent a reset command to the bus.

I had been searching for an USB-ETH which is not based on a Realtek chip. No luck.

Sorry for ranting :-)
