### ISSUE TITLE
Should get-updates, refresh, and update commands be in fwupdtool?

### ISSUE THREAD

**Issue by superm1** [hughsie/fwupd#535]
Mostly a discussion question right now.

If the answer is no, then flatpak'ed and snap'ed fwupdtool probably also shouldn't ship any remotes when daemon is false.

**Comment by hughsie** [comment]
`fwupdtool refresh` can't really be implemented, as the tool needs to be run as root, and we can't really download things as root in any sane way. `get-updates` could be implemented, but that means either the containerized fwupd needs to have read access to the host `remotes.d` directory (possible in flatpak) or we'd ask the user to download the files as the user and then just squirt the fd's into the daemon. `update` is hard too, also because of the downloading and the need to refresh metadata.

My gut feeling here would be not to ship the remotes, and leave cache and remote management out of fwupdtool.

**Comment by superm1** [comment]
> fwupdtool refresh can't really be implemented, as the tool needs to be run as root, and we can't really download things as root in any sane way.

What about forking the process and dropping permissions on the fork for the download?

**Comment by hughsie** [comment]
> What about forking the process and dropping permissions on the fork for the download?

Sure, technically possible just a load more code. I think "here's an cabinet archive for your hardware, use this command line to install it on your hardware" is a valid use case. I don't think we want to give the impression that things are all magically going to work (including front-end UIs) with a containerized `fwupdtool` -- but it does give us a huge get-out-of-jail card when trying to support older distros.

**Comment by superm1** [comment]
Sounds good to me.
